name: veracode-demo

on:
  workflow_dispatch:
  #schedule:
  #- cron: "4 5 * * *"

jobs:
  veracode-demo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
    
      - name: build with maven
        
        run: |
          mvn clean package
     
      - name: save artifact
        uses: actions/upload-artifact@main
        with:
            name: scan-target
            path: ./target/verademo.war

      - name: setup veracode
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          
      - name: package app
        run: |
          ./veracode package -s . -a
          
      - name: sast scan
      
    #break the build?
        continue-on-error: true
        
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
          
        run: | 
          ./veracode static scan ./target/verademo.war --summary-output sast-summary.txt
          cat sast-summary.txt
      
      - name: upload sast artifact
        uses: actions/upload-artifact@main
        with:
          name: SAST-App-Issues-${{ github.run_id }}
          path: "*.json"
          
      - name: sca scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        working-directory: .
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --json=SCA-App-Issues.json --allow-dirty
          
      - name: upload sca issues artifact
        uses: actions/upload-artifact@v4
        with:
          name: SCA-App-Issues-${{ github.run_id }}
          path: "SCA-App-Issues.json"

      - name: get scan results
        uses: actions/download-artifact@v1
        with:
          name: SAST-App-Issues-${{ github.run_id }}

      - name: debug action
        run: |
           pwd
           ls -al
           whoami
           find . -name pom.xml
           find . -name verademo.war
           find . -name *zip
           find . -name *json

          
      - name: convert pipeline scan output to SARIF format
        id: convert
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v1.0.7
        with:
          results-json: filtered_results.json
          output-results-sarif: veracode-results.sarif
          source-base-path-1: "^com/veracode:src/main/java/com/veracode"
          source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
          repo_owner: OWNER
          repo_name: REPO
          commitSHA: 4b6472266afd7b471e86085a6659e8c7f2b119da
          ref: refs/heads/master
          githubToken: ${{ secrets.GTOKEN }}
          
      - name: output sarif results
        run: |
           cat veracode-results.sarif
