name: veracode-sca-sast

on:
  workflow_dispatch:
  # Uncomment the following lines to enable scheduled runs
  #schedule:
  #- cron: "4 5 * * *"

jobs:
  checkout-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
    
      - name: Build with Maven
        working-directory: ./app/
        run: pwd
             ls -al
             mvn clean package

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-target
          path: app/target/verademo.war
          
  sast-scan:
    needs: checkout-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Veracode
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      - name: Package App
        run: |
          ./veracode package -s . -a
      - name: debug1
        run: |
          pwd
          ls -al
          whoami
          df -h
          find . -name verademo.war
          find . -name *zip
      - name: SAST Scan
        continue-on-error: false
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
          ls -la ./app/target/verademo.war
          ./veracode static scan ./app/target/verademo.war --summary-output sast-summary.txt
          cat sast-summary.txt
      
      - name: Upload SAST issues artifact
        uses: actions/upload-artifact@main
        with:
          name: SAST-App-Issues-${{ github.run_id }}
          path: "*.json"
           
  sca-scan:
    needs: sast-scan
    runs-on: ubuntu-latest
    steps:
      - name: debug1
        run: |
          pwd
          ls -al
          whoami
          df -h
          time
      - name: SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        working-directory: ./app
        run: |
          pwd
          ls -al
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --json=SCA-App-Issues.json
      - name: Upload SCA issues artifact
        uses: actions/upload-artifact@v4
        with:
          name: SCA-App-Issues-${{ github.run_id }}
          path: "SCA-App-Issues.json"
