name: veracode-demo

on:
  workflow_dispatch:
  # Uncomment the following lines to enable scheduled runs
  #schedule:
  #- cron: "4 5 * * *"

jobs:
  checkout-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
    
      - name: build with maven
        
        run: |
          mvn clean package

      - name: debug action
        run: |
          pwd
          ls -al
          whoami
          find . -name pom.xml
          find . -name verademo.war
          find . -name *zip

    #  - name: save artifact
    #    uses: actions/upload-artifact@v4
    #   with:
    #      name: scan-target
    #     path: ./app/target/verademo.war

      - name: Setup Veracode
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          
      - name: Package App
        run: |
          ./veracode package -s . -a
          
      - name: SAST Scan
        continue-on-error: true
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: |
          veracode static scan ./target/verademo.war --summary-output sast-summary.txt
          cat sast-summary.txt
      
      - name: Upload SAST issues artifact
        uses: actions/upload-artifact@main
        with:
          name: SAST-App-Issues-${{ github.run_id }}
          path: "*.json"
          
      - name: SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        working-directory: ./app
        run: |
          pwd
          ls -al
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --json=SCA-App-Issues.json
      - name: Upload SCA issues artifact
        uses: actions/upload-artifact@v4
        with:
          name: SCA-App-Issues-${{ github.run_id }}
          path: "SCA-App-Issues.json"
