name: veracode-demo

on:
  workflow_dispatch:
  #schedule:
  #- cron: "4 5 * * *"

jobs:
  veracode-demo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
    
      - name: build with maven
        run: |
          mvn clean package
     
      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-target
          path: ./target/verademo.war

      - name: setup veracode
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          
      - name: package app
        run: |
          ./veracode package -s . -a
          
      - name: sast scan
        continue-on-error: true
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
        run: | 
          ./veracode static scan ./target/verademo.war --summary-output sast-summary.txt
          cat sast-summary.txt
      
      - name: upload sast artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAST-App-Issues-${{ github.run_id }}
          path: "*.json"
          
      - name: sca scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        working-directory: .
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --json=SCA-App-Issues.json --allow-dirty
          
      - name: upload sca issues artifact
        uses: actions/upload-artifact@v4
        with:
          name: SCA-App-Issues-${{ github.run_id }}
          path: "SCA-App-Issues.json"

      - name: get scan results
        uses: actions/download-artifact@v4
        with:
          name: SAST-App-Issues-${{ github.run_id }}
          
      - name: convert pipeline scan output to SARIF format
        continue-on-error: true
        id: convert
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.2
        with:
          results-json: results.json
          output-results-sarif: veracode-results.sarif
          source-base-path-1: "^com/veracode:src/main/java/com/"
          source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
          ref: refs/heads/main
          githubToken: ${{ secrets.GTOKEN }}

      - name: debug
        run: | 
          ls
          
      - uses: github/codeql-action/upload-sarif@v3
        with:
       
          sarif_file: veracode-results.sarif
                
      - name: save filtered results file
        uses: actions/upload-artifact@v4
        with:
          name: filtered-results
          path: results.json
      
      - name: create fixes from static findings
        uses: Veracode/veracode-fix@main
        with:
          inputFile: results.json
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          source_base_path_1: "com/:src/main/java/com/"
          source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
          language: java
          prComment: true
          fixType: single
